### ISSUE TITLE
Error in using LDheatmap.addGenes()

### ISSUE THREAD

**Issue by Jay4BioPZ** [mcneney/LDheatmap#11]
Hi there, 

I am running a GWAS workflow following an online tutorial. With the following code to create an LDheatmap, there is an error message for LDheatmap.addGenes()

The code
`
ld <- ld(subgen, subgen, stats="R.squared") # Find LD map of CETP SNPs
ll <- LDheatmap(ld, CETP$position, flip=TRUE, name="myLDgrob", title=NULL)
llplusgenes <- LDheatmap.addGenes(ll, chr = "chr16", genome = "hg19", genesLocation = 0.01)
` 

The console return
`
llplusgenes <- LDheatmap.addGenes(ll, chr = "chr16", genome = "hg19")
Error in errorHandler(responseError) : Bad Request
In addition: Warning message:
In .local(x, ...) :
  'track' parameter is deprecated now you go by the 'table' instead
                Use ucscTables(genome, track) to retrieve the list of tables for a track
`

Do you know what could the problem be?

p.s., I am using Rstudio with R 4.3.0.

**Comment by mcneney** [comment]
Hi,
The error originates from the Bioconductor package rtracklayer, which we rely on for gene tracks. Unfortunately this package is undergoing changes and we're having trouble keeping up with them. I'll ask one of the other LDheatmap developers to get back to you on this.

Brad

**Comment by Jay4BioPZ** [comment]
Hi,
Great! I am looking forward to that. Indeed, I am using the rtracklayer package (version 1.59.1, recently installed through `BiocManager::install`. By the way, I am referring to [this GWAS tutorial](https://github.com/AAlhendi1707/GWAS/blob/master/Post-analytic-visualization-and-genomic-interrogation.md#heatmap). I hope the information helps :) 

If changing the package version helps, please also let me know.

Best,
Jay

**Comment by gloriayxf** [comment]
Hi Jay,

Both plotGenes() and LDheatmap.addGenes() functions in the LDheatmap package are currently unavailable due to an issue with the ucscTableQuery() function in the rtracklayer package. Specifically, the ucscTableQuery() function is unable to fetch the "kgXref" and "kgColor" tables we need for plotting Genes. (as reported in the following GitHub issue: https://github.com/lawremi/rtracklayer/issues/27)

Unfortunately, both plotGenes() and LDheatmap.addGenes() functions are unavailable this time. Sorry about any inconvenience and our team is actively working on resolving this issue as soon as possible. 

Sincerely,
Gloria

**Comment by Jay4BioPZ** [comment]
I see. I think I will wait for the latest update of the package. Thanks for the effort!
